In [14]:
import pandas as pd
import datetime

import numpy as np

In [15]:
df_master = pd.read_csv("../datasources/master_dataset.csv")
df_master.head()

,date,rate,sent_fin_us_uncertainty,sent_fin_us_litigious,sent_fin_us_strong_modal,sent_fin_us_weak_modal,sent_fin_us_constraining,sent_fin_us_optimistic,ti_rate_rsi_14,ti_rate_stochrsi_14,...,index_WGTS.COAL,index_WGTS.FISH,index_WGTS.FOPR,index_WGTS.MTLS,index_WGTS.NATURALGAS,index_WGTS.WCC,index_WGTS.WTI,us_bank_rate,sent_bert_us_fin,sent_bert_us_gen
0,1955-08-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25,NaN,NaN
1,1955-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25,NaN,NaN
2,1955-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25,NaN,NaN
3,1955-08-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25,NaN,NaN
4,1955-08-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25,NaN,NaN

### Set Label for each row

In [16]:
df_master['y_exp'] = np.full(df_master.shape[0], -1)

for i, row in df_master.iterrows():
    try:
        two_weeks_from_current_date = datetime.datetime.strptime(row.date, "%Y-%m-%d") + datetime.timedelta(weeks=2)

        futur_rate = list(df_master.loc[df_master['date'] == str(two_weeks_from_current_date.date())].rate)[0]
        df_master.loc[i, 'y_exp' ] = futur_rate
    except: 
        break

df_master = df_master.loc[df_master.y_exp >= 0]

In [17]:
df_master= df_master.dropna()
df_master= df_master.reset_index(drop=True)

In [18]:
df_master

,date,rate,sent_fin_us_uncertainty,sent_fin_us_litigious,sent_fin_us_strong_modal,sent_fin_us_weak_modal,sent_fin_us_constraining,sent_fin_us_optimistic,ti_rate_rsi_14,ti_rate_stochrsi_14,...,index_WGTS.FISH,index_WGTS.FOPR,index_WGTS.MTLS,index_WGTS.NATURALGAS,index_WGTS.WCC,index_WGTS.WTI,us_bank_rate,sent_bert_us_fin,sent_bert_us_gen,y_exp
0,1993-02-03,1.2645,41.0,18.0,4.0,15.0,18.0,-39.0,38.212401,0.048874,...,1.622854,28.884246,18.050559,11.346407,5.603417,11.797081,6.00,0.431132,0.913638,1.2596
1,1993-02-04,1.2672,41.0,18.0,4.0,15.0,18.0,-39.0,42.427864,0.211060,...,1.622854,28.884246,18.050559,11.346407,5.603417,11.797081,6.00,0.431132,0.913638,1.2643
2,1993-02-05,1.2618,41.0,18.0,4.0,15.0,18.0,-39.0,36.992024,0.001922,...,1.622854,28.884246,18.050559,11.346407,5.603417,11.797081,6.00,0.431132,0.913638,1.2606
3,1993-02-08,1.2618,41.0,18.0,4.0,15.0,18.0,-39.0,36.992024,0.001922,...,1.622854,28.884246,18.050559,11.346407,5.603417,11.797081,6.00,0.431132,0.913638,1.2603
4,1993-02-09,1.2630,41.0,18.0,4.0,15.0,18.0,-39.0,39.006023,0.079408,...,1.622854,28.884246,18.050559,11.346407,5.603417,11.797081,6.00,0.431132,0.913638,1.2590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7736,2022-10-17,1.3877,13.0,9.0,2.0,7.0,5.0,-2.0,66.914006,0.441181,...,0.902375,9.560856,17.131522,6.758784,24.702028,26.021942,6.25,0.514009,0.979710,1.3615
7737,2022-10-18,1.3714,13.0,9.0,2.0,7.0,5.0,-2.0,57.140333,0.034251,...,0.902375,9.560856,17.131522,6.758784,24.702028,26.021942,6.25,0.514009,0.979710,1.3625
7738,2022-10-19,1.3741,13.0,9.0,2.0,7.0,5.0,-2.0,58.228710,0.090386,...,0.902375,9.560856,17.131522,6.758784,24.702028,26.021942,6.25,0.514009,0.979710,1.3632
7739,2022-10-20,1.3767,20.0,6.0,6.0,12.0,2.0,-26.0,59.300511,0.145665,...,0.902375,9.560856,17.131522,6.758784,24.702028,26.021942,6.25,0.514009,0.979710,1.3712
7740,2022-10-21,1.3766,20.0,6.0,6.0,12.0,2.0,-26.0,59.237554,0.264550,...,0.902375,9.560856,17.131522,6.758784,24.702028,26.021942,6.25,0.514009,0.979710,1.3746

In [19]:
df = df_master
df = df.replace('.', np.nan)
df[[" us_bank_rate"]] = df[[" us_bank_rate"]].apply(pd.to_numeric)
df = df.rename(columns={' us_bank_rate': 'us_bank_rate'})
df = df.dropna()

## Prepare data for LSTM

In [20]:
# Split train val test datasets
test_cutting_date = '2022-08-01'
val_cutting_date = '2022-05-01'
df_train = df[df['date'] < val_cutting_date]
df_val = df[(df['date'] >= val_cutting_date) & (df['date'] < test_cutting_date)]
df_test = df[df['date'] >= test_cutting_date]

In [21]:
def split_Xy(df):
    return df.drop(columns=['y_exp']), df['y_exp']

X_train, y_train = split_Xy(df_train)
X_val, y_val = split_Xy(df_val)
X_test, y_test = split_Xy(df_test)

In [23]:
def to_batch(df, y):
    # Put data in batches
    sliding_window_size = 20

    data = []
    for i in range(sliding_window_size, len(df)):
        sample = df.iloc[i-sliding_window_size:i]
        sample = sample.drop(columns=['date']) # date is not relevant
        data.append(sample.values)
    data = np.array(data)
    return data, y[sliding_window_size:]

X_train, y_train = to_batch(X_train, y_train)
X_val, y_val = to_batch(X_val, y_val)
X_test, y_test = to_batch(X_test, y_test)

## Train model

In [25]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.datasets import imdb
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np
from keras import optimizers

def train_lstm_model(X_train,y_train, X_val,y_val, verbose=2):
    print('Build model...')
    model = Sequential()
    model.add(LSTM(60, input_shape=X_train.shape[1:]))
    model.add(Dense(32))
    model.add(Dense(1))
    optimizer = optimizers.Adam(clipnorm=0.1)
    model.compile(loss='mean_squared_error', optimizer=optimizer)
    monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, 
                            verbose=1, mode='auto', restore_best_weights=True)

    info = model.fit(X_train,y_train,validation_data=(X_val,y_val),
            callbacks=[monitor],verbose=verbose,epochs=100)
    return model, info


model, _ = train_lstm_model(X_train,y_train, X_val,y_val)

Build model...
Train...
Epoch 1/100
230/230 - 6s - loss: 0.0243 - val_loss: 0.0382 - 6s/epoch - 25ms/step
Epoch 2/100
230/230 - 3s - loss: 0.0051 - val_loss: 0.0130 - 3s/epoch - 11ms/step
Epoch 3/100
230/230 - 3s - loss: 0.0044 - val_loss: 0.0297 - 3s/epoch - 12ms/step
Epoch 4/100
230/230 - 3s - loss: 0.0046 - val_loss: 0.0411 - 3s/epoch - 13ms/step
Epoch 5/100
230/230 - 2s - loss: 0.0038 - val_loss: 0.0485 - 2s/epoch - 10ms/step
Epoch 6/100
230/230 - 2s - loss: 0.0050 - val_loss: 0.0578 - 2s/epoch - 10ms/step
Epoch 7/100
Restoring model weights from the end of the best epoch: 2.
230/230 - 2s - loss: 0.0046 - val_loss: 0.0320 - 2s/epoch - 10ms/step
Epoch 7: early stopping

# Search features

In [ ]:

for i in range(X_train.shape[-1]):

## Evaluate model performances

In [38]:
from  tensorflow.keras.metrics import mean_squared_error
y_pred = model(X_test)
mean_squared_error(y_test.to_numpy(), y_pred.numpy().reshape(-1))